language: python

python:
  - "3.6"

addons:
  postgresql: "9.6"

services:
  - postgresql
  - redis-server

install:
  - pip install -r requirements.txt
  - pip install coverage

cache: pip

script:
  - coverage run manage.py test
  - coverage report
