language: python

python:
  - "3.6"

addons:
  postgresql: "9.6"

services:
  - postgresql

install: "pip install -r requirements.txt"

cache: pip

before_script:
  - psql -U postgres -c 'create database rest_fuzzy;'

script:
  - coverage run example/manage.py test
  - coverage report
