# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=32768),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=32768, null=True),
        ),
    ]
